version: "2.0"

services:
  nginx:
    image: nginx
    container_name: nginx-ppt
    restart: always
    ports:
      - "80:80"
    expose:
      - "8000"
    volumes:
      - ../nginx_conf/papertime:/etc/nginx/conf.d
      - ./:/var/www/html
    networks:
      projetos_servicos:
        ipv4_address: 10.11.0.21

  php:
    build: ./
    container_name: php-ppt
    command: bash -c "php-fpm --allow-to-run-as-root"
    restart: always
    volumes:
      - ./:/var/www/html
    expose:
      - "9000"
    networks:
      projetos_servicos:
        ipv4_address: 10.11.0.22

networks:
  projetos_servicos:
    external: true